# -*- coding: utf-8 -*-
"""Cópia de Imersao_dados_4_aula01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYDA15VtMg3UCIijSnfc6LWw07JVBEee
"""

import pandas as pd
url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"
dados = pd.read_csv(url)

dados.head()

dados.sample(10)

dados.info()

dados["Bairro"][6522]

dados.Metragem.mean()

dados["Metragem"].mean()

sum((dados["Bairro"] == "Vila Mariana"))

tem_imoveis_vila =( dados["Bairro"] == "Vila Mariana")
tem_imoveis_vila

imoveis_vila_mariana = dados[tem_imoveis_vila]
imoveis_vila_mariana

imoveis_vila_mariana["Metragem"].mean()

dados["Bairro"].value_counts()

n_imoveis_bairro = dados["Bairro"].value_counts()
n_imoveis_bairro.head(10).plot.bar()

"""Desafios:

1 - Realizar a média da metragem para cara um dos bairros (Paulo)

2 - 2 formas de selecionar os dados por bairro (consultar os métodos na documentação do pandas) (Thiago)

3 - Explorar alguns gráficos na documentação e aplicar nas demais colunas do DF, tentar colocar alguma conclusão (Thiago)

4 - Pegar outros estatísticas dos dados, média, mediana, mim, max (Vivi)

5 - Descobrir quais são os bairros que não tem nome de Rua. (Vivi)
"""

# 1. Realizar a média da metragem para cara um dos bairros
aux = dados.groupby("Bairro")
aux["Metragem"].mean()

# OBS:groupby = Agrupe DataFrame usando um mapeador ou por uma série de colunas.
# OBS1:mean = Retorna a média dos valores sobre o eixo solicitado.

# 1. Realizar a média da metragem para cara um dos bairros
aux = dados.groupby("Bairro")
aux["Metragem"].describe()

# OBS:groupby = Agrupe DataFrame usando um mapeador ou por uma série de colunas.
# OBS1:describe = Gerar estatísticas descritivas.

# 2. Formas de selecionar os dados por bairro
aux = dados.groupby("Bairro")
aux.mean()

# 2. Formas de selecionar os dados por bairro
aux = dados[dados['Bairro'] == 'Aclimação']
aux

#3. Explorar alguns gráficos na documentação e aplicar nas demais colunas do DF
dados[["Bairro","Quartos","Banheiros"]].sample(12).groupby("Bairro").mean().plot.line()

##3. Explorar alguns gráficos na documentação e aplicar nas demais colunas do DF
dados[["Bairro","Quartos","Banheiros"]].sample(10).groupby("Bairro").max().plot.bar()

#4. Pegar outros estatísticas dos dados, média, mediana, mim, max
dados["Metragem"].mean(), dados["Metragem"].median(), dados["Metragem"].min(), dados["Metragem"].max()

#4. Pegar outros estatísticas dos dados, média, mediana, mim, max
dados["Quartos"].describe()

#4. Pegar outros estatísticas dos dados, média, mediana, mim, max
dados["Metragem"].describe()

#5. Descobrir quais são os bairros que não tem nome de Rua
dados[dados["Rua"].isna()].describe()

#5. Descobrir quais são os bairros que não tem nome de Rua
dados[dados["Rua"].isna()].groupby("Bairro")["Bairro"].unique().values